### ISSUE TITLE
Doesn't work on iPad/iPhone

### ISSUE THREAD

**Issue by msveshnikov** [bence-toth/react-hook-screen-orientation#20]
undefined is not an object (evaluating 'window.screen.orientation.type')

Similar to:

https://github.com/akamai/boomerang/issues/214

**Comment by bence-toth** [comment]
Thank you for your kind contribution @msveshnikov, this has now been released with [v1.0.4](https://github.com/bence-toth/react-hook-screen-orientation/releases/tag/v1.0.4)
